backend:
  name: git-gateway
  branch: main
  identity_url: 'https://moormixdigital.netlify.app/.netlify/identity'
  gateway_url: 'https://moormixdigital.netlify.app/.netlify/git'

local_backend: true
media_folder: "img"
public_folder: "/img"
publish_mode: editorial_workflow

collections:
  - name: "products"
    label: "Productos"
    folder: "data/products"
    create: true
    slug: "{{fields.name}}"
    fields:
      - {label: "Nombre del Producto", name: "name", widget: "string"}
      - {label: "Precio", name: "price", widget: "number"}
      - {label: "Descripción", name: "description", widget: "markdown"}
      - {label: "Imagen Principal", name: "image", widget: "image"}
      - {label: 'Precio a crédito', name: 'credit_price', widget: 'number'}
- {label: 'Descripción del crédito', name: 'credit_description', widget: 'string'}
