backend:
  name: github
  repo: MOORMIX-DIGITAL/Moormix1
  branch: main
  auth_type: pkce # Esto es más seguro y fiable
  app_id: Ov23linMVS5JUXJ4PcE1 # Tu app_id debe ir solo, sin texto extra

local_backend: true
media_folder: "img"
public_folder: "/img"
publish_mode: editorial_workflow

collections:
  - name: "products"
    label: "Productos"
    folder: "data/products"
    create: true
    slug: "{{fields.name}}"
    fields:
      - {label: "Nombre del Producto", name: "name", widget: "string"}
      - {label: "Precio", name: "price", widget: "number"}
      - {label: "Descripción", name: "description", widget: "markdown"}
      - {label: "Imagen Principal", name: "image", widget: "image"}
      - {label: 'Precio a crédito', name: 'credit_price', widget: 'number'}
