backend:
  name: git-gateway
  branch: main
  identity_url: 'https://moormixdigital.netlify.app/.netlify/identity'
  gateway_url: 'https://moormixdigital.netlify.app/.netlify/git'

local_backend: true
media_folder: "img"
public_folder: "/img"
publish_mode: editorial_workflow

collections:
  - name: "products"
    label: "Productos"
    folder: "data/products"
    create: true
    slug: "{{fields.name}}"
    - name: 'contact-messages'
    label: 'Mensajes de Contacto'
    folder: '_data/contact-messages'
    create: true
    fields:
      - {label: 'Nombre', name: 'name', widget: 'string'}
      - {label: 'Email', name: 'email', widget: 'string'}
      - {label: 'Mensaje', name: 'message', widget: 'text'}
    fields:
    - label: 'Detalles técnicos'
        name: 'specs'
        widget: 'list'
        fields:
          - {label: 'Nombre del detalle', name: 'name', widget: 'string'}
          - {label: 'Descripción', name: 'description', widget: 'string'}
    - label: 'Estado'
        name: 'status'
        widget: 'select'
        options: ['En Stock', 'Agotado']
      - {label: "Nombre del Producto", name: "name", widget: "string"}
      - {label: "Precio", name: "price", widget: "number"}
      - {label: "Descripción", name: "description", widget: "markdown"}
      - label: 'Galería de imágenes'
        name: 'gallery'
        widget: 'list'
        fields:
          - {label: 'Imagen', name: 'image', widget: 'image'}
      - {label: 'Precio a crédito', name: 'credit_price', widget: 'number'}
- {label: 'Descripción del crédito', name: 'credit_description', widget: 'string'}
- label: 'Categoría'
        name: 'category'
        widget: 'relation'
        collection: 'categories'
        value_field: 'title'
        search_fields: ['title']
- name: 'categories'
    label: 'Categorías'
    folder: 'content/categories'
    create: true
    fields:
      - {label: 'Título de la Categoría', name: 'title', widget: 'string'}
